// Names are displayed in all three languages; the historical descriptions are in English.
export const LANDMARK_STORIES = {
  lotus: {
    tamil:'கொழும்பு தாமரை கோபுரம்', era:'Opened to visitors · 2022', category:'Observation & communications',
    introduction:'A lotus blossom above Beira Lake, bringing the city’s skyline and waterfront into one view.',
    history:'Construction began in 2012, and the tower opened to the public on 15 September 2022. The project combines broadcasting infrastructure with spaces for visitors, exhibitions and hospitality.',
    architecture:'A slender stem rises to a rounded tower house wrapped in petal forms. The lotus silhouette gives the building its identity, while observation spaces look across the lake, the Indian Ocean and the city.',
    significance:'The tower connects a familiar floral symbol with contemporary engineering. Its observation deck offers a way to understand Colombo’s geography from above.',
    sources:[{label:'Lotus Tower · official history',url:'https://colombolotustower.lk/ta/our-story/'}],
  },
  altair: {
    tamil:'அல்டெயர்', era:'Completed · 2021', category:'Residential architecture',
    introduction:'Two towers in conversation: one upright, the other stepping toward it above the lake.',
    history:'Designed by Safdie Architects for Indocean Developers, Altair is recorded by the architect as a completed 2021 project. The development brings residential towers and a waterfront retail promenade to Beira Lake.',
    architecture:'A leaning tower meets a vertical tower, creating a cascade of garden terraces. The diagonal structural frame supports open interior layouts, while the paired forms allow apartments to receive light and cross-ventilation.',
    significance:'Altair explores how a tall residential building can offer outdoor space and a relationship with the waterfront. The terraces and shared sky garden are central to that idea.',
    sources:[{label:'Safdie Architects · Altair Residences',url:'https://www.safdiearchitects.com/projects/altair-residences'}],
  },
  gangaramaya: {
    tamil:'கங்காராமய விகாரை', era:'Founded · late 19th century', category:'Buddhist temple & learning',
    introduction:'A living place of worship, learning and cultural activity within Colombo’s busy streets.',
    history:'The temple traces its beginnings to the scholar monk Hikkaduwe Sri Sumangala Nayaka Thera in the late nineteenth century. Later generations developed its religious, educational and community work.',
    architecture:'The main temple is a compound of shrines, courtyards, sculpture and museum collections, rather than a single hall. This model represents the land-based compound; the separate Seema Malaka pavilion stands on Beira Lake.',
    significance:'Gangaramaya combines daily religious practice with teaching and community services. Its collections and ceremonial spaces reflect the many roles a city temple can play.',
    sources:[{label:'Gangaramaya · official history',url:'https://gangaramaya.com/about/'},{label:'Gangaramaya · temple and services',url:'https://gangaramaya.com/'}],
  },
  wtc: {
    tamil:'உலக வர்த்தக மையம்', era:'Opened · 1997', category:'Commercial landmark',
    introduction:'A pair of office towers marking the commercial heart of Colombo Fort.',
    history:'The World Trade Center Colombo formally opened on 12 October 1997. Its developer’s archive follows construction from the early 1990s through the opening of the completed complex.',
    architecture:'Two 39-storey office towers are joined by a four-storey retail podium. Repeating horizontal bands and curved glazed faces give the pair a unified appearance while the podium connects them at street level.',
    significance:'The complex houses local and international businesses and participates in the World Trade Centers Association network. Its twin silhouette has become a recognizable part of the Fort skyline.',
    sources:[{label:'World Trade Center Colombo · official history',url:'https://wtc.lk/about/'}],
  },
  fort: {
    tamil:'கொழும்பு கோட்டை புகையிரத நிலையம்', era:'Opened · 1917', category:'Railway heritage',
    introduction:'A historic entrance to the city, where an ornate clock façade meets the daily rhythm of rail travel.',
    history:'Colombo Fort station opened in 1917. The public ticket hall leads toward the platforms, with footbridges connecting the station’s different boarding areas. The forecourt also contains a memorial to Henry Steel Olcott.',
    architecture:'The street façade is distinguished by its curved clock pediment, balustrades and scalloped canopy. Behind it, long platform roofs rest on slender columns and metal trusses. Sinhala and English signs make the entrance immediately recognizable.',
    significance:'Fort is a major point of arrival, departure and interchange in Colombo. The station brings an everyday public service into a building whose historic character remains visible from the street.',
    sources:[{label:'Seat 61 · station guide and photographs',url:'https://www.seat61.com/SriLanka.htm#colombo-fort-station'},{label:'Station reconstruction · visual references',url:'/landmarks/fort/REFERENCES.md'}],
  },
  museum: {
    tamil:'கொழும்பு தேசிய அருங்காட்சியகம்', era:'Founded · 1877', category:'National heritage & collections',
    introduction:'White arcades, shaded verandas and galleries devoted to Sri Lanka’s cultural heritage.',
    history:'The Colombo Museum opened on 1 January 1877 under Governor William Henry Gregory. Public Works Department architect J. G. Smither prepared the Italian-style design, and construction was completed in 1876.',
    architecture:'A symmetrical two-storey façade brings together a three-arched portico, classical pediments, balustrades and deep upper verandas. Inside, a broad wooden stair reaches a landing and divides into two returning flights.',
    significance:'The museum preserves and presents Sri Lanka’s cultural and natural heritage. Its ground-floor galleries follow a historical sequence, while upper galleries are organized around themes.',
    sources:[{label:'Sri Lanka Tourism · National Museum',url:'https://srilanka.travel/national-museum'},{label:'Explore Sri Lanka · architecture and interiors',url:'https://exploresrilanka.lk/the-colombo-national-museum/'}],
  },
  galle_face_green: {
    tamil: 'காலி முகத்திடல்', era: 'Established · 1859', category: 'Oceanfront promenade & cultural ground',
    introduction: 'A mile-long coastal green facing the rolling surf of the Indian Ocean, where Colombo gathers at twilight.',
    history: 'Laid out in 1859 by Governor Sir Henry George Ward for horse racing and recreational walks, Galle Face Green is Sri Lanka’s most famous public ocean promenade. Through colonial times to modern independence, it has served as the beloved open-air gathering place for kite flying, cricket, and seaside dining.',
    architecture: 'The expansive rectangular seaside green stretches between Fort and Kollupitiya along the Indian Ocean coastline. An ocean-facing concrete sea wall and paved promenade provide unbroken views of breaking waves, while street-food stalls serving iconic Isso Vadai line the southern walking terrace.',
    significance: 'Galle Face Green remains Colombo’s premier democratic public space, uniting families, vendors, and sunset watchers. It frames the dramatic visual contrast between the eternal Indian Ocean surf and the surging modern skyline of One Galle Face and Port City.',
    sources: [{label: 'Sri Lanka Tourism · Galle Face Green', url: 'https://srilanka.travel/galle-face-green'}],
  },
  one_galle_face: {
    tamil: 'ஒன் காலி முகத்திடல்', era: 'Opened · 2019', category: 'Mixed-use & luxury hospitality',
    introduction: 'Twin 194-metre glass towers and the Shangri-La Hotel commanding the Galle Face shoreline.',
    history: 'Developed by the Shangri-La Group and officially opened in 2019, One Galle Face is Sri Lanka’s largest integrated development. It transformed the oceanfront corridor adjacent to the historic green into an international commercial, residential, and luxury retail epicentre.',
    architecture: 'Designed with soaring curtain-wall facades, the complex features twin 51-storey residential towers flanking an extensive seven-storey retail podium and office tower. Its gleaming high-performance reflective glazing reflects the shifting colors of the Indian Ocean and Colombo sunsets.',
    significance: 'The towers mark Colombo’s emergence as a modern South Asian financial and lifestyle hub. Standing directly opposite the ocean surf, they redefine the city’s western skyline and offer panoramic views across the port and Beira Lake.',
    sources: [{label: 'Shangri-La Group · One Galle Face', url: 'https://www.onegalleface.com/about'}],
  },
  galle_face_hotel: {
    tamil: 'காலி முக ஹோட்டல்', era: 'Founded · 1864', category: 'Colonial heritage hospitality',
    introduction: 'The Grand Dame of Ceylon, standing proudly on the Indian Ocean edge since 1864.',
    history: 'Founded in 1864 by four British entrepreneurs on the site of a former Dutch villa, the Galle Face Hotel is one of the oldest and most legendary hotels east of Suez. It has hosted royalty, world leaders, and authors including Arthur C. Clarke, who wrote the final chapters of 3001: The Final Odyssey here.',
    architecture: 'Exemplifying Victorian and colonial revival architecture, the hotel features wide arcaded verandas, polished teak floors, a grand chequerboard terrace, and an oceanfront saltwater pool kissed by sea spray. Restorations have preserved its historic ballrooms and antique maritime artifacts.',
    significance: 'The hotel embodies over a century and a half of Sri Lankan hospitality and heritage. The sunset flag-lowering ceremony on the ocean lawn accompanied by lone bagpipe melodies remains one of Colombo’s most cherished daily rituals.',
    sources: [{label: 'Galle Face Hotel · Heritage Archive', url: 'https://gallefacehotel.com/history/'}],
  },
  'galle-face-hotel': {
    tamil: 'காலி முக ஹோட்டல்', era: 'Founded · 1864', category: 'Colonial heritage hospitality',
    introduction: 'The Grand Dame of Ceylon, standing proudly on the Indian Ocean edge since 1864.',
    history: 'Founded in 1864 by four British entrepreneurs on the site of a former Dutch villa, the Galle Face Hotel is one of the oldest and most legendary hotels east of Suez. It has hosted royalty, world leaders, and authors including Arthur C. Clarke, who wrote the final chapters of 3001: The Final Odyssey here.',
    architecture: 'Exemplifying Victorian and colonial revival architecture, the hotel features wide arcaded verandas, polished teak floors, a grand chequerboard terrace, and an oceanfront saltwater pool kissed by sea spray. Restorations have preserved its historic ballrooms and antique maritime artifacts.',
    significance: 'The hotel embodies over a century and a half of Sri Lankan hospitality and heritage. The sunset flag-lowering ceremony on the ocean lawn accompanied by lone bagpipe melodies remains one of Colombo’s most cherished daily rituals.',
    sources: [{label: 'Galle Face Hotel · Heritage Archive', url: 'https://gallefacehotel.com/history/'}],
  },
  cinnamon_life: {
    tamil: 'சினமன் லைஃப் · சிட்டி ஆஃப் ட்ரீம்ஸ்', era: 'Opened · 2024', category: 'Integrated resort & sculptural architecture',
    introduction: 'Cecil Balmond’s landmark architectural masterpiece reshaping the Beira Lake waterfront.',
    history: 'Envisioned as Sri Lanka’s first multi-billion dollar integrated lifestyle resort, Cinnamon Life at City of Dreams was designed by world-renowned Sri Lankan-British architect Cecil Balmond. Opening in stages through 2024, the complex integrates hospitality, gaming, arts, and living.',
    architecture: 'The complex is distinguished by its dramatic cantilevered volumes, pixelated crystalline facades, and striking geometric bridge structures spanning high above ground. Balmond utilized algorithmic fractal geometry to echo traditional Sri Lankan gem facets and woven textiles in modern steel and glass.',
    significance: 'Cinnamon Life redefines the architectural ambitions of Sri Lanka. Positioned between Beira Lake and the Galle Face corridor, it serves as an urban bridge connecting the historical commercial core with the expanding waterfront entertainment district.',
    sources: [{label: 'City of Dreams Sri Lanka · Architecture & Design', url: 'https://www.cinnamonhotels.com/cinnamonlife'}],
  },
  port_city: {
    tamil: 'கொழும்பு துறைமுக நகரம்', era: 'Reclamation · 2014-Present', category: 'Master-planned financial peninsula',
    introduction: 'A 269-hectare reclaimed maritime metropolis extending Colombo into the Indian Ocean.',
    history: 'Initiated as a landmark coastal reclamation project, Port City Colombo added 269 hectares of newly engineered land west of Galle Face and the Colombo Port. Developed as a special economic zone and international financial centre, it represents the largest foreign direct investment in Sri Lankan history.',
    architecture: 'Engineered with massive offshore breakwaters, artificial coastal lagoons, sandy recreational beaches, and a dedicated yacht marina. The master plan integrates sustainable transit corridors, landscaped pedestrian seawalls, and climate-resilient high-density commercial towers.',
    significance: 'Port City positions Colombo as a strategic maritime gateway and financial crossroads along the main east-west Indian Ocean shipping route. It dramatically shifts Sri Lanka’s geographical boundary into deep blue waters.',
    sources: [{label: 'Port City Colombo · Official Master Plan', url: 'https://www.portcitycolombo.lk/master-plan'}],
  },
  'jami-ul-alfar': {
    tamil: 'ஜாமி உல்-அல்ஃபார் பள்ளிவாசல்', era: 'Constructed · 1908', category: 'Indo-Saracenic religious heritage',
    introduction: 'The candy-striped pomegranate landmark rising above the vibrant bazaars of Pettah.',
    history: 'Commissioned in 1908 by the local Indian Muslim community and designed by Habibu Labbe Saibu Labbe, the Jami Ul-Alfar Mosque was completed in 1909. Before modern skyscrapers, its striking red-and-white minarets served as the nautical beacon guiding maritime sailors into Colombo Harbour.',
    architecture: 'The mosque is a tour-de-force of Indo-Saracenic and Gothic revival aesthetics, renowned for its hypnotic glazed brickwork alternating in crimson and pristine white swirls, checks, and chevrons. Slender minarets topped with pomegranate-shaped onion domes crown the dense multi-tiered sanctuary.',
    significance: 'Jami Ul-Alfar is one of Colombo’s most globally recognized architectural icons and a vibrant house of worship welcoming thousands daily. Its vibrant presence in Pettah celebrates Sri Lanka’s multicultural mercantile legacy.',
    sources: [{label: 'Jami Ul-Alfar Mosque · Colombo Heritage Guide', url: 'https://srilanka.travel/colombo-jami-ul-alfar'}],
  },
  'old-parliament': {
    tamil: 'பழைய நாடாளுமன்ற கட்டிடம்', era: 'Opened · 1930', category: 'Colonial civic & legislative heritage',
    introduction: 'A monumental Neo-Baroque sandstone palace facing Galle Face Green, serving as the seat of governance for over half a century.',
    history: 'Constructed in 1930 as the Legislative Council of Ceylon under British rule, the building was designed by chief architect Austin Woodeson of the Public Works Department. It served as Ceylon’s House of Representatives and later the Parliament of Sri Lanka until the new parliament was built in Kotte in 1982. Today it houses the Presidential Secretariat.',
    architecture: 'Built in the Neo-Baroque architectural style from warm buff sandstone, the building is distinguished by a grand ceremonial central staircase, a monumental hexastyle portico with six fluted Ionic columns supporting a triangular pediment with the national seal, and a graceful central dome and cupola lantern.',
    significance: 'The Old Parliament stands as the political crucible of modern Sri Lanka, where independence was celebrated and national legislation was enacted. Facing the open lawns of Galle Face Green, its classical facade anchors the city’s ceremonial core.',
    sources: [{label: 'Presidential Secretariat of Sri Lanka · History', url: 'https://www.presidentsoffice.gov.lk/history/'}],
  },
  'independence-hall': {
    tamil: 'சுதந்திர நினைவு மண்டபம்', era: 'Completed · 1953', category: 'National monument & ceremonial hall',
    introduction: 'An open stone pillared pavilion at Independence Square commemorating Sri Lanka’s freedom from British colonial rule in 1948.',
    history: 'Erected to mark Sri Lanka’s independence on 4 February 1948, the hall was designed by an esteemed committee of Sri Lankan architects led by Tom Neville Wynne-Jones. Construction concluded in 1953, creating an enduring national sanctuary for ceremonial events and celebrations.',
    architecture: 'Modelled on the celebrated Magul Maduwa (Royal Audience Hall) of Kandy, the structure features a four-tiered stepped granite plinth guarded by stone lions (Singha). Sixty elaborately sculpted granite columns support a sweeping double-pitched Kandyan terracotta hip roof lined with traditional carved valance boarding (vali bihibu).',
    significance: 'Independence Memorial Hall is the architectural emblem of Sri Lankan sovereignty, reuniting ancient Kandyan craftsmanship with modern civic pride. Its spacious park and walking tracks make it a cherished public retreat in Cinnamon Gardens.',
    sources: [{label: 'Department of National Archives · Independence Hall', url: 'https://archives.gov.lk/independence-hall'}],
  },
  'town-hall': {
    tamil: 'கொழும்பு நகர மண்டபம்', era: 'Opened · 1928', category: 'Neoclassical civic palace',
    introduction: 'Colombo’s pristine white Neoclassical civic palace and municipal headquarters, affectionately known as the "White House of Ceylon".',
    history: 'Commissioned by the Colombo Municipal Council and designed by British architect S. J. Edwards, construction commenced in 1924 and concluded in 1928. It replaced the older town hall in Pettah and has housed the city mayor and municipal administration ever since.',
    architecture: 'Drawing inspiration from the United States Capitol and St. Paul’s Cathedral, Town Hall features a symmetrical facade with giant Corinthian porticoes, colonnaded wings, and an imposing central drum with clock dials crowned by a magnificent ribbed dome and open lantern cupola rising 42 metres.',
    significance: 'As the seat of Sri Lanka’s oldest municipal council (established 1865), Town Hall is the administrative heart of Colombo. Situated directly opposite Viharamahadevi Park, its brilliant white silhouette is an unmistakable civic icon.',
    sources: [{label: 'Colombo Municipal Council · Official Portal', url: 'https://www.colombo.mc.gov.lk/'}],
  },
  'clock-tower': {
    tamil: 'கோட்டை மணிக்கூண்டு மற்றும் கலங்கரை விளக்கம்', era: 'Constructed · 1857', category: 'Victorian civic & maritime monument',
    introduction: 'A 29-metre Victorian masonry clock tower at Chatham Street that once operated as Colombo’s primary maritime lighthouse.',
    history: 'Designed by Lady Elizabeth Ward (wife of Governor Sir Henry Ward) and completed in 1857, this historic landmark predates Big Ben’s clock mechanism in London. John Moore & Sons of Clerkenwell crafted the clockwork in 1872, and the tower projected a lighthouse beacon visible 17 miles out to sea until modern harbour lights took over.',
    architecture: 'Built from rustic ashlar limestone and brick quoins, the square tower features open arched pedestrian portals at its base, three tiers of louvered belfry openings, four illuminated clock dials, an observation balcony with corbels, and a glazed lantern room capped by a copper dome and wind vane.',
    significance: 'It is the only lighthouse in the world that also served as a four-dial municipal clock tower in the middle of a bustling urban thoroughfare. Situated in Fort, it reflects the maritime and civic transformation of 19th-century Ceylon.',
    sources: [{label: 'Sri Lanka Navy · Maritime Heritage of Fort Lighthouse', url: 'https://www.navy.lk/lighthouse-heritage.html'}],
  },
  red_mosque: {
    tamil: 'ஜமி உல்-அல்பார் பள்ளிவாசல்', era: 'Constructed · 1908', category: 'Indo-Saracenic religious heritage',
    introduction: 'The candy-striped pomegranate landmark rising above the vibrant bazaars of Pettah.',
    history: 'Commissioned in 1908 by the local Indian Muslim community and designed by Habibu Labbe Saibu Labbe, the Jami Ul-Alfar Mosque was completed in 1909. Before modern skyscrapers, its striking red-and-white minarets served as the nautical beacon guiding maritime sailors into Colombo Harbour.',
    architecture: 'The mosque is a tour-de-force of Indo-Saracenic and Gothic revival aesthetics, renowned for its hypnotic glazed brickwork alternating in crimson and pristine white swirls, checks, and chevrons. Slender minarets topped with pomegranate-shaped onion domes crown the dense multi-tiered sanctuary.',
    significance: 'Jami Ul-Alfar is one of Colombo’s most globally recognized architectural icons and a vibrant house of worship welcoming thousands daily. Its vibrant presence in Pettah celebrates Sri Lanka’s multicultural mercantile legacy.',
    sources: [{label: 'Jami Ul-Alfar Mosque · Colombo Heritage Guide', url: 'https://srilanka.travel/colombo-jami-ul-alfar'}],
  },
  'sambodhi-chaithya': {
    tamil: 'சம்போதி சைத்தியம்', era: 'Completed · 1956', category: 'Modern Buddhist maritime monument',
    introduction: 'A soaring 47-metre Buddhist stupa elevated on a four-legged parabolic arch over Marine Drive at the entrance to Colombo Port.',
    history: 'Conceived by venerated monk Most Ven. Henpitagedara Gnanasiha Thero and commissioned to celebrate the 2500th Buddha Jayanti in 1956, Sambodhi Chaithya was engineered by legendary Sri Lankan engineer Dr. A. N. S. Kulasinghe. Built atop a daring reinforced concrete parabolic arch spanning Chaitya Road, it was designed to be the first beacon visible to mariners approaching Colombo by sea.',
    architecture: 'Rising 47 metres into the sky, the stupa is supported on four colossal reinforced concrete parabolic arch legs allowing vehicular traffic to pass freely underneath. A central elevator and stairway shaft ascends 28 metres to a wide circular viewing deck, above which sits a classical bell-shaped stupa dome (Garbhaya), square harmika, a 13-ring conical spire, and a gleaming gold pinnacle with crystal tip.',
    significance: 'Sambodhi Chaithya is a triumph of Sri Lankan structural prestressed engineering and spiritual heritage, offering panoramic vistas across Colombo Harbour, the Port City breakwater, and the Indian Ocean horizon.',
    sources: [{label: 'Sri Lanka Ports Authority · Sambodhi Chaithya Heritage', url: 'https://www.slpa.lk/port-heritage/'}],
  },
  'nelum-pokuna': {
    tamil: 'நெலும் பொகுண மஹிந்த ராஜபக்ஷ திரையரங்கு', era: 'Opened · 2011', category: 'Contemporary performing arts centre',
    introduction: 'Colombo’s premier national performing arts theatre, sculpted in the shape of an eight-petaled stylized lotus pond in Cinnamon Gardens.',
    history: 'Inaugurated in December 2011 on Nelum Pokuna Mawatha (Green Path), the theatre was designed by the Beijing Institute of Architectural Design (BIAD) in collaboration with Sri Lankan architects. It stands as a cultural bridge commemorating ancient Sinhalese hydrological design traditions.',
    architecture: 'The exterior architecture is directly inspired by the 12th-century Nelum Pokuna (lotus pond) built by King Parakramabahu the Great in Polonnaruwa. Eight sweeping, curved white petal shells overlap around a central auditorium core, crowned with a translucent turquoise glass dome. The entrance features a dramatic 3-tiered granite plaza with reflecting water pools, monumental glazed foyer, and 1,288-seat state-of-the-art auditorium with a mechanized revolving stage.',
    significance: 'As Sri Lanka’s modern cultural landmark, Nelum Pokuna hosts world-class symphonies, theatrical productions, and national arts festivals. Its sculptural floral form anchors Colombo’s Green Path arts precinct.',
    sources: [{label: 'Nelum Pokuna Mahinda Rajapaksa Theatre · Official', url: 'https://nelumpokuna.com/'}],
  },
  'harbour-cranes': {
    tamil: 'கொழும்பு துறைமுகம் மற்றும் கொள்கலன் முனையங்கள்', era: 'Expanded · 1980–Present', category: 'Maritime trade & deepwater port',
    introduction: 'The bustling container hub of South Asia, framed by monumental Ship-to-Shore gantry cranes and deep-water ocean berths.',
    history: 'A strategic stop along the historic Maritime Silk Route for over two millennia, Colombo Harbour was transformed into a sheltered artificial port in the 1870s under British chief engineer Sir John Coode. In the modern era, the Jaya, South Asia Gateway (SAGT), and Colombo International Container Terminals (CICT) transformed it into one of the world’s top 25 busiest transshipment container ports.',
    architecture: 'The northern port skyline is defined by colossal 75-metre Ship-to-Shore (STS) container gantry cranes painted in vibrant crimson and white hazard stripes, sweeping cantilever booms, heavy rail tracks, and colorful multi-tiered container stacks alongside ocean freighters and tugboats.',
    significance: 'Colombo Port is the commercial lifeblood of Sri Lanka and a pivotal maritime crossroads connecting Europe, the Middle East, East Asia, and Africa across the Indian Ocean.',
    sources: [{label: 'Sri Lanka Ports Authority · Container Terminal Overview', url: 'https://www.slpa.lk/'}],
  },
};


